In [3]:
! pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/16/c6/75231fd47afd6b3f89011e7077f1a3958441264aca7ae9ff596e3276a5d0/pandas-2.2.2-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached pandas-2.2.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (19 kB)
  Obtaining dependency information for numpy>=1.23.2 from https://files.pythonhosted.org/packages/d1/d8/597b4b2e396a77cbec677c9de33bb1789d5c3b66d653cb723d00eb331e99/numpy-2.0.1-cp311-cp311-macosx_14_0_arm64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 78.2 kB/s eta 0:00:00a 0:00:01
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/9c/3d/a121f284241f08268b21359bd425f7d4825cffc5ac5cd0e1b3d82ffd2b10/pytz-2024.1-py2.py3-none-any.whl.metadata
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/65/58/f9c9e6be752e9fcb8b6a0

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_insurance = pd.read_csv('contribution_rates.csv')
df_insurance.head()

Period  Contribution Rate (%)  Yearly Increase (%)
0   1970                    8.2                  NaN
1   1975                   10.5            28.048780
2   1980                   11.4             8.571429
3   1985                   11.8             3.508772
4   1990                   12.5             5.932203

In [4]:
df_zusatz = pd.read_csv('additional_contribution_rates_with_increase.csv')
df_zusatz.head()

Year  Average Additional Contribution Rate (%)  Yearly Increase (%)
0  2015                                      0.83                  NaN
1  2016                                      1.08            30.120482
2  2017                                      1.11             2.777778
3  2018                                      1.08            -2.702703
4  2019                                      0.99            -8.333333

In [5]:
insurance_increase = df_insurance['Yearly Increase (%)'].values[1:]
insurance_increase

array([28.04878049,  8.57142857,  3.50877193,  5.93220339,  5.6       ,
        2.27272727,  0.74074074,  2.94117647,  2.14285714, -0.6993007 ,
        0.        ,  0.        ,  0.        ,  4.22535211,  0.67567568,
        4.02684564, -3.87096774,  4.02684564, -5.80645161,  0.        ,
        0.        ,  0.        ,  0.        ])

In [11]:
renteanpassung = pd.read_csv('rentenanpassung-verbraucherpreisindex.csv', sep=';')
renteanpassung.head()

Jahr  Rentenanpassung West  Rentenanpassung Ost  Verbraucherpreisindex
0  2009                  2.41                 3.38                    0.3
1  2010                  0.00                 0.00                    1.1
2  2011                  0.99                 0.99                    2.1
3  2012                  2.18                 2.26                    2.0
4  2013                  0.25                 3.29                    1.4

In [6]:
zusatz_increase = df_zusatz['Yearly Increase (%)'].values[1:]
zusatz_increase

array([30.12048193,  2.77777778, -2.7027027 , -8.33333333,  1.01010101,
       28.        ,  6.25      , 11.02941176, 12.58278146])

In [21]:
zusatz_percentage = df_zusatz['Average Additional Contribution Rate (%)'].values
zusatz_percentage

array([0.83, 1.08, 1.11, 1.08, 0.99, 1.  , 1.28, 1.36, 1.51, 1.7 ])

In [26]:
df = pd.read_csv('gkv_contribution_rates.csv')
df['BBG (Month)'] = df['BBG (Month)'] / 100
df.index = df['Year']
df = df.drop(columns=['Year'])
df.head()

BBG (Month)  BBG (Year) Average GKV Contribution Rate (%)
Year                                                           
2023       4987.5     59850.0                              14,6
2022       4837.5     58050.0                              14,6
2021       4837.5     58050.0                              14,6
2020       4687.5     56250.0                              14,6
2019       4537.5     54450.0                              14,6

In [13]:
hochstbeitrag_2024 = 843
age_2024 = 30
age_rente = 72
expected_life = 90
rente_anspruch = 2500

zusatz_percent_2024 = df_zusatz["Average Additional Contribution Rate (%)"].iloc[-1]
zusatz_value = 5175 * (zusatz_percent_2024/100)


In [17]:
# one simulation
beitrag = hochstbeitrag_2024
zusatz = zusatz_value
zusatz_percent = zusatz_percent_2024
rente = rente_anspruch
for year in range(age_2024, age_rente):
#     yearly_increace = np.random.choice(insurance_increase)
#     zusatz_yearly = np.random.choice(zusatz_percentage)
#     rente_increase = np.random.choice(renteanpassung['Rentenanpassung West'].values)
#     # print(f"Year {year}: {yearly_increace:.2f}, {zusatz_yearly_increase:.2f}")

#     beitrag = beitrag * (1 + yearly_increace / 100)
#     zusatz = zusatz * (1 + zusatz_yearly_increase / 100)

#     rente = rente * (1 + rente_increase / 100)

#     print(f"Year {year}: {beitrag:.2f} + {zusatz:.2f} = {beitrag + zusatz:.2f}")

# for year in range(age_rente, expected_life):
#     rente_increase = np.random.choice(renteanpassung['Rentenanpassung West'].values)
#     rente = rente * (1 + rente_increase / 100)

#     zusatz_yearly_increase = np.random.choice(zusatz_increase)

    

    # gkv_preis = ((14.6) / 100) * rente 

    # print(f"Year {year}: {rente:.2f}, {gkv_preis:.2f}")

Year 30: 861.06 + 97.68 = 958.74
Year 31: 861.06 + 100.39 = 961.46
Year 32: 861.06 + 106.67 = 967.73
Year 33: 861.06 + 136.53 = 997.60
Year 34: 861.06 + 145.07 = 1006.13
Year 35: 912.14 + 146.53 = 1058.68
Year 36: 912.14 + 187.56 = 1099.70
Year 37: 963.22 + 199.28 = 1162.51
Year 38: 963.22 + 255.08 = 1218.31
Year 39: 963.22 + 331.91 = 1295.14
Year 40: 925.94 + 431.89 = 1357.82
Year 41: 945.78 + 436.25 = 1382.03
Year 42: 985.74 + 399.89 = 1385.64
Year 43: 1070.23 + 511.87 = 1582.10
Year 44: 1008.09 + 666.04 = 1674.13
Year 45: 1050.69 + 707.67 = 1758.36
Year 46: 1050.69 + 688.54 = 1739.23
Year 47: 1057.79 + 669.93 = 1727.72
Year 48: 1057.79 + 857.52 = 1915.30
Year 49: 1102.48 + 1097.62 = 2200.10
Year 50: 1102.48 + 1428.23 = 2530.71
Year 51: 1094.77 + 1858.42 = 2953.19
Year 52: 1156.08 + 2378.77 = 3534.85
Year 53: 1180.85 + 3044.83 = 4225.68
Year 54: 1206.16 + 2962.54 = 4168.69
Year 55: 1254.73 + 3854.87 = 5109.59
Year 56: 1254.73 + 3750.68 = 5005.41
Year 57: 1254.73 + 3438.12 = 4692.85
Y

In [18]:
zusatz_percent

np.float64(273.38757544314785)